# Generated by Django 3.0 on 2021-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211117_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cartquantity',
            field=models.IntegerField(default=0),
        ),
    ]
